# Generated by Django 5.0.6 on 2026-07-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationDetails',
            fields=[
                ('edu_id', models.AutoField(db_column='EDU_ID', primary_key=True, serialize=False)),
                ('degree', models.CharField(db_column='DEGREE', max_length=100)),
                ('specialization', models.CharField(blank=True, db_column='SPECIALIZATION', max_length=50, null=True)),
                ('college_name', models.CharField(blank=True, db_column='COLLEGE_NAME', max_length=50, null=True)),
                ('university', models.CharField(blank=True, db_column='UNIVERSITY', max_length=100, null=True)),
                ('passing_year', models.IntegerField(blank=True, db_column='PASSING_YEAR', null=True)),
                ('cgpa', models.DecimalField(blank=True, db_column='CGPA', decimal_places=1, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'education_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('emp_id', models.AutoField(db_column='EMP_ID', primary_key=True, serialize=False)),
                ('employee_code', models.CharField(blank=True, db_column='EMPLOYEE_CODE', max_length=20, null=True, unique=True)),
                ('department', models.CharField(blank=True, db_column='DEPARTMENT', max_length=50, null=True)),
                ('salary', models.IntegerField(blank=True, db_column='SALARY', null=True)),
                ('experience_years', models.IntegerField(blank=True, db_column='EXPERIENCE_YEARS', null=True)),
                ('joining_date', models.DateField(blank=True, db_column='JOINING_DATE', null=True)),
            ],
            options={
                'db_table': 'employee_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalaryDetails',
            fields=[
                ('salary_id', models.AutoField(db_column='SALARY_ID', primary_key=True, serialize=False)),
                ('monthly_salary', models.IntegerField(blank=True, db_column='MONTHLY_SALARY', null=True)),
                ('yearly_salary', models.IntegerField(blank=True, db_column='YEARLY_SALARY', null=True)),
                ('monthly_tax', models.IntegerField(blank=True, db_column='MONTHLY_TAX', null=True)),
                ('yearly_tax', models.IntegerField(blank=True, db_column='YEARLY_TAX', null=True)),
                ('net_monthly_salary', models.IntegerField(blank=True, db_column='NET_MONTHLY_SALARY', null=True)),
                ('net_yearly_salary', models.IntegerField(blank=True, db_column='NET_YEARLY_SALARY', null=True)),
            ],
            options={
                'db_table': 'salary_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='FIRST_NAME', max_length=100, unique=True)),
                ('last_name', models.CharField(db_column='LAST_NAME', max_length=100, unique=True)),
                ('age', models.IntegerField(blank=True, db_column='AGE', null=True)),
                ('gender', models.CharField(blank=True, db_column='GENDER', max_length=50, null=True)),
                ('email', models.CharField(blank=True, db_column='EMAIL', max_length=100, null=True, unique=True)),
                ('phn_number', models.CharField(blank=True, db_column='PHN_NUMBER', max_length=10, null=True)),
                ('city', models.CharField(blank=True, db_column='CITY', max_length=50, null=True)),
                ('pofession', models.CharField(blank=True, db_column='POFESSION', max_length=50, null=True)),
            ],
            options={
                'db_table': 'personal_details',
                'managed': True,
            },
        ),
    ]
